ns:
  build: .
  volumes:
    - ".cion_key_data:/etc/bind/keys:rw"
    - ".cion_zone_files:/var/bind/dyn:rw"
    - "./public:/public:rw"

  ports:
    - "1234:80/tcp"
    - "5553:53/udp"
    - "5553:53/tcp"

  environment:
    CION_ROOT_DOMAIN: foo.bar
    CION_WEB_ADDRESS: 127.0.0.1
    # set the port if not default
    CION_WEB_PORT: 1234
    # http/https
    CION_WEB_PROTO: http
    CION_NS1_ADDRESS: 127.0.0.1
    # set the port if not default
    CION_NS1_PORT: 5553
    CION_NS2_ADDRESS: 127.0.0.1
    # set the port if not default
    CION_NS2_PORT: 5553
    CION_NS1_HOSTNAME: ns1
    CION_NS2_HOSTNAME: ns2