#!/bin/bash

zone="$1"
value="$2"

[[ -z $zone ]] && echo "Missing parameter: zone" && exit 1
[[ -z $value ]] && echo "Missing parameter: value" && exit 1

CION_ROOT_DOMAIN="${CION_ROOT_DOMAIN:-foo.bar}"
CION_TTL="${CION_TTL:-180}"
CION_DEPLOY_UPDATE="${CION_DEPLOY_UPDATE}"
CION_DELETE_ONLY="${CION_DELETE_ONLY}"

record_update() {
    IFS=$'\n' old_records=( $(dig @localhost ${zone}.${CION_ROOT_DOMAIN} TXT +short | grep "^${value}$") )
    
    echo "server 127.0.0.1"
    echo "zone ${CION_ROOT_DOMAIN}"

    for old_record in "${old_records[@]}"; do
        echo "update delete ${zone}.${CION_ROOT_DOMAIN}. ${CION_TTL} IN TXT ${old_record}"
    done
    if [[ -z ${CION_DELETE_ONLY} ]]; then
        echo "update add ${zone}.${CION_ROOT_DOMAIN}. ${CION_TTL} IN TXT \"${value}\""
    fi
    echo "send"
    echo "quit"
}

if [[ -n $CION_DEPLOY_UPDATE ]]; then
    record_update | nsupdate -k named.conf.rndc
else
    record_update
fi
