#!/bin/bash

zone="$1"
pref="$2"
name="$3"

[[ -z $zone ]] && echo "Missing parameter: zone" && exit 1
[[ -z $pref ]] && echo "Missing parameter: pref" && exit 1
[[ -z $name ]] && echo "Missing parameter: name" && exit 1

CION_ROOT_DOMAIN="${CION_ROOT_DOMAIN:-foo.bar}"
CION_TTL="${CION_TTL:-180}"
CION_DEPLOY_UPDATE="${CION_DEPLOY_UPDATE}"
CION_DELETE_ONLY="${CION_DELETE_ONLY}"

record_update() {
    if [[ -z ${CION_DELETE_ONLY} ]]; then
        IFS=$'\n' old_records=( $(dig @localhost ${zone}.${CION_ROOT_DOMAIN} MX +short | grep "^${pref} ") )
    else
        IFS=$'\n' old_records=( $(dig @localhost ${zone}.${CION_ROOT_DOMAIN} MX +short | grep "^${pref} ${name}$") )
    fi

    echo "server 127.0.0.1"
    echo "zone ${CION_ROOT_DOMAIN}"

    for old_record in "${old_records[@]}"; do
        echo "update delete ${zone}.${CION_ROOT_DOMAIN}. ${CION_TTL} IN MX ${old_record}"
    done
    if [[ -z ${CION_DELETE_ONLY} ]]; then
        echo "update add ${zone}.${CION_ROOT_DOMAIN}. ${CION_TTL} IN MX ${pref} ${name}"
    fi
    echo "send"
    echo "quit"
}

if [[ -n $CION_DEPLOY_UPDATE ]]; then
    record_update | nsupdate -k named.conf.rndc
else
    record_update
fi
