#!/bin/bash

shopt -s nullglob

CION_CONF_ROOT="${CION_CONF_ROOT:-/etc/bind}"
CION_CONF_PATH="${CION_CONF_PATH:-/etc/bind/zones}"
CION_ZONE_PATH="${CION_ZONE_PATH:-/var/bind/dyn}"
CION_ROOT_DOMAIN="${CION_ROOT_DOMAIN:-foo.bar}"
CION_TTL="${CION_TTL:=180}"
CION_NS_HOSTNAME="${CION_NS_HOSTNAME:-ns}"
CION_NS_ADDRESS="${CION_NS_ADDRESS:-127.0.0.1}"

CION_RNDC_RELOAD="${CION_RNDC_RELOAD:-true}"

mkdir -p "${CION_ZONE_PATH}"

rm -rf "${CION_CONF_PATH}/*.conf"
IFS=$'\n' keys=( $(cion_list_keys) )
for key in ${keys[@]}; do
    username="${key% *}"
    key=${key##* }
    zone="${username}.${CION_ROOT_DOMAIN}"
    config_file="${CION_CONF_PATH}/${zone}.conf"
    zone_file="${CION_ZONE_PATH}/${zone}.zone"

    (
        echo "zone \"${zone}\" IN {"
        echo "  type master;"
        echo "  file \"/var/bind/dyn/${zone}.zone\";"
        echo "  allow-update { 127.0.0.1; };"
        echo "};"
    ) > "${config_file}"
    chown named. "${config_file}"

    if [[ ! -f "${zone_file}" ]]; then
        timestamp="$(date +%Y%m%d)"
        (
            echo "\$TTL ${CION_TTL}"
            echo "@       IN      SOA     ns.${zone}. root.${zone}.  ("
            echo "      ${timestamp}01 ; Serial"
            echo "      28800      ; Refresh"
            echo "      14400      ; Retry"
            echo "      604800     ; Expire - 1 week"
            echo "      86400 )    ; Minimum"
            echo "@ IN NS ${CION_NS_HOSTNAME}"
            echo "${CION_NS_HOSTNAME} IN A ${CION_NS_ADDRESS}"
        ) > "${zone_file}"
        chown named. "${zone_file}"
    fi
done

:> "${CION_CONF_ROOT}/named.conf.zones"
    if [[ ${#keys[@]} > 0 ]]; then
    cat ${CION_CONF_PATH}/*.conf >> "${CION_CONF_ROOT}/named.conf.zones"
fi

chown named. -R "${CION_ZONE_PATH}"
$CION_RNDC_RELOAD && rndc reload